b2b/urls.py
#!python
# -*- coding: utf8 -*-


from django.conf.urls import url
from views import *


urlpatterns = [
    url(r'register/$', register, name="b2b_register"),
]

grill/urls.py
#!python
# -*- coding: utf8 -*-

""" Адреса уровня проекта

grill URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sample/', include('sample.urls')),
    url(r'^', include('b2c.urls')),
    url(r'^user/', include('logit.urls')),
    url(r'^user/', include('django.contrib.auth.urls'), name="login"),
    url(r'', include('content.urls')),
    url(r'^redactor', include('redactor.urls')),
    url(r'^paypal', include('paypal.standard.ipn.urls')),
    url(r'^', include('transactions.urls')),
    url(r'^market/', include('market.urls')),
    url(r'^b2b/', include('b2b.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^accounts/', include('account.urls')),
    url(r'^comments/', include('comments.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

b2b/models.py
#!python
# -*- coding: utf8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User


class Printer(User):
    user = models.OneToOneField(User, null=False)
    name = models.CharField(_(u'Название компании'), max_length=30)
    middle_name = models.CharField(_(u'Отчество'), default='', blank=True, max_length=30)
    address = models.CharField(_(u'Адрес'), max_length=500)
    phone = models.CharField(_(u'Контактный номер телефона'), max_length=15)
    website = models.URLField(_(u'Вебсайт'))
    services = models.CharField(_(u'Услуги'), max_length=50)
    lat = models.FloatField(_(u'Широта'))
    lon = models.FloatField(_(u'Долгота'))
    logo = models.ImageField(_(u'Логотип'), upload_to="printers", blank=True)
    categories = models.ManyToManyField('b2b.Categories', verbose_name=u'Категории')
    tags = models.ManyToManyField('b2b.Tags', verbose_name=u'Теги')
    subscribed = models.BooleanField(_(u'Подписка активна'), default=False)
    sub_expires = models.DateTimeField(_(u'Подписка истекает'), null=True)
    metro = models.CharField(_(u'Метро'), max_length=150, blank=True)
    schedule = models.CharField(_(u'Время работы'), max_length=150, blank=True)

    class Meta:
        verbose_name = _(u'Печатник')
        verbose_name_plural = _(u'Печатники')

    def __unicode__(self):
        return u'%s' % (self.name)


class Categories(models.Model):
    category = models.CharField(_(u'Категория'), max_length=50)

    class Meta:
        verbose_name = _(u'Категория')
        verbose_name_plural = _(u'Категории')

    def __unicode__(self):
        return u'%s' % (self.category)


class Tags(models.Model):
    tag = models.CharField(_(u'Тег'), max_length=50)
    cat = models.ManyToManyField(
        'b2b.Categories', verbose_name=u'Категории'
    )

    class Meta:
        verbose_name = _(u'Тег')
        verbose_name_plural = _(u'Теги')

    def __unicode__(self):
        return u'%s' % (self.tag)

b2b/forms.py
#!python
# -*- coding: utf8 -*-

from models import *
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from django import forms

class b2bCForm(UserCreationForm):
    class Meta:
        model = Printer
        fields = ('username', 'password1', 'address', 'password2', 'name', 'schedule', 'metro', 'first_name', 'middle_name', 'last_name', 'phone', 'email', 'website', 'services',
                   'lat', 'lon', 'logo', 'categories', 'tags')

    def __init__(self, *args, **kwargs):
        super(b2bCForm, self).__init__(*args, **kwargs)
        # add common css class to all widgets
        for field in iter(self.fields):
            # get current classes from Meta
            classes = self.fields[field].widget.attrs.get("class")
            if classes is not None:
                classes += " form-control"
            else:
                classes = "form-control"
            self.fields[field].widget.attrs.update({
                "class": classes
            })
        self.fields['username'].help_text = _(u'<ul><li>Обязательное поле. Не более 30 символов. Только английские буквы, цифры и символы @/./+/-/_.</li></ul>')
        self.fields['phone'].help_text = _(u'<ul><li>Указанный телефон будет виден всем пользователям.</li></ul>')
        self.fields['tags'].help_text = _(u'<ul><li>Для выбора нескольких тегов зажмите Ctrl.</li></ul>')
        self.fields['categories'].help_text = _(u'<ul><li>Для выбора нескольких категорий зажмите Ctrl.</li></ul>')
        self.fields['password2'].help_text = _(u'<ul><li>Для подтверждения введите, пожалуйста, пароль ещё раз.</li></ul>')
        self.fields['address'].widget = forms.HiddenInput()
        self.fields['lat'].widget = forms.HiddenInput()
        self.fields['lon'].widget = forms.HiddenInput()

b2b/views.py
#!python
# -*- coding: utf8 -*-

from django.contrib import auth
from django.shortcuts import redirect, render
from forms import b2bCForm
from django.template.context_processors import csrf
from b2b.models import Printer, Tags


def register(request):
    args = {}
    args.update(csrf(request))

    tags = Tags.objects.distinct()
    mystring = ''
    for tag in tags:
        mydict = u'%d:%s' % (tag.id, '[' + (", ".join(str(p.id) for p in tag.cat.all())) + ']')
        mystring = u'%s, %s' % (mystring, mydict)

    args['tags'] = '{%s}' % (mystring[2:])

    args['printers'] = b2bCForm
    if request.POST:
        printer_form = b2bCForm(request.POST, request.FILES)
        if printer_form.is_valid():
            printer_form.logo = request.FILES
            printer_form.save()
            printer_form.save_m2m()
            newuser = auth.authenticate(
                username=printer_form.cleaned_data['username'],
                password=printer_form.cleaned_data['password1'])
            auth.login(request, newuser)
            return redirect('user_profile')

        else:
            args['printers'] = printer_form
    return render(request, 'rstr/register.html', args)

b2b/templates/rstr/register.html
{% extends "base.html" %}

{% block headtitle %}
    Регистрация
{% endblock %}

{% block headertext %}
    <h1>Регистрация</h1>
{% endblock %}

{% block content %}
    <div class="bloke-register-b2b col-xs-6 col-sm-6">
<form enctype="multipart/form-data" method="post">
{% csrf_token %}
<dl class="register">

{% for field in printers.visible_fields %}
    <dt>{{ field.label_tag }}</dt>
    <dd class="clearfix">{{ field }}
    {% if field.help_text %}<div class="clearfix help-block">{{ field.help_text |safe }}</div>{% endif %}
    {% if field.errors %}<div class="myerrors clearfix">{{ field.errors |safe}}</div>{% endif %}
    </dd>
{% endfor %}

{% for field in printers.hidden_fields %}
     <div style="display:none;">{{ field }}</div>
{% endfor %}


<div id="floating-panel">
      <input id="address" list="addresslist" type="textbox", class="form-control" value="Москва, Россия">
      <datalist id="addresslist">
      </datalist>
      <input id="submit-geocode" type="button" value="Проверить адрес">
</div>
        <div class="iframe-container">
    <div id="map"></div>
        </div>
</dl>

<input type="submit" value="Зарегистрироваться" class="clearfix btn btn-success logit">
</form>

    </div>



{% endblock %}

{% block javascript %}

<script src="http://maps.google.com/maps/api/js?key=AIzaSyCIC6deUmipx1i53t2ncZlP7MUTeQ52qvY&language=ru&region=RU"></script>


<script>

$(function() {
    $('#id_categories').change(function() {
        var selected = $('#id_categories').find(":selected"),
            optionDict = {{ tags |safe }};
        $('#id_tags option').each( function() {
            this.selected=false;
            $(this).hide();
            self = $(this);
            $('#id_categories :selected').each( function(i, val) {
                if ($.inArray(parseInt($(val).val()), optionDict[$(self).val()]) != -1){
                    $(self).show();
                }
            });
        });
    });
});
function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 8,
    center: {lat: 55.755826, lng: 37.6173}
  });
  var geocoder = new google.maps.Geocoder();
  var marker = new google.maps.Marker({
        map: map,
        position: {lat: 55.755826, lng: 37.6173},
        draggable:true
      });

   google.maps.event.addListener(marker, 'dragend', function()
{
    geocodePosition(marker.getPosition());
});

  document.getElementById('submit-geocode').addEventListener('click', function() {
    geocodeAddress(geocoder, map, marker);
  });
}

function geocodeAddress(geocoder, resultsMap, marker) {
  var address = document.getElementById('address').value;
  geocoder.geocode({'address': address}, function(results, status) {
    if (status === google.maps.GeocoderStatus.OK) {
      resultsMap.setCenter(results[0].geometry.location);
      marker.setPosition(results[0].geometry.location);
      $('#id_address').val(results[0].formatted_address);
      $('#id_lat').val(results[0].geometry.location.lat);
      $('#id_lon').val(results[0].geometry.location.lng);

      $('#addresslist').empty();
      for (i in results) {
        $('#addresslist').append("<option value='" + results[i].formatted_address + "'>");
      }
    } else {
      alert('Такого адреса не существует: ' + status);
    }
  });
}

function geocodePosition(pos)
{
   geocoder = new google.maps.Geocoder();
   geocoder.geocode
    ({
        latLng: pos
    },
        function(results, status)
        {
            if (status == google.maps.GeocoderStatus.OK)
            {
                $("#address").val(results[0].formatted_address);
                $("#mapErrorMsg").hide(100);
                $('#id_address').val(results[0].formatted_address);
                $('#id_lat').val(results[0].geometry.location.lat);
                $('#id_lon').val(results[0].geometry.location.lng);
            }
            else
            {
                $("#mapErrorMsg").html('Такого адреса не существует: '+status).show(100);
            }
        }
    );
}

window.onload = function() {
    $('#id_logo').removeClass('form-control');
    $('#id_tags option').each( function() {$(this).hide();});
    initMap();
}
</script>



{% endblock %}