b2b/urls.py
#!python
# -*- coding: utf8 -*-


from django.conf.urls import url
from views import *


urlpatterns = [
    url(r'register/$', register, name="b2b_register"),
]

chat/urls.py
#!python
# -*- coding: utf8 -*-


from django.conf.urls import url
from views import *

urlpatterns = [
    url('^chat_id_(?P<id>\d+)/$', chat_view, name="chat"),
    url('^ajax/test', ajax_view, name="chat_ajax")
]

grill/urls.py
#!python
# -*- coding: utf8 -*-

""" Адреса уровня проекта

grill URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sample/', include('sample.urls')),
    url(r'^', include('b2c.urls')),
    url(r'^user/', include('logit.urls')),
    url(r'^user/', include('django.contrib.auth.urls'), name="login"),
    url(r'', include('content.urls')),
    url(r'^redactor', include('redactor.urls')),
    url(r'^paypal', include('paypal.standard.ipn.urls')),
    url(r'^', include('transactions.urls')),
    url(r'^market/', include('market.urls')),
    url(r'^b2b/', include('b2b.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^accounts/', include('account.urls')),
    url(r'^comments/', include('comments.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
#!python
# -*- coding: utf8 -*-

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from b2c.models import Order
from django.utils import timezone


class ChatMessage(models.Model):
    sender = models.ForeignKey(User, null=True)
    order = models.ForeignKey(Order, null=True)
    date = models.DateTimeField(default=timezone.now)
    message = models.TextField()

chat/forms.py
#!python
# -*- coding: utf8 -*-

from django.forms import ModelForm
from django import forms
from models import ChatMessage


class ChatMessageForm(ModelForm):
    class Meta:
        model = ChatMessage
        exclude = ['date']
        widgets = {
            'message': forms.Textarea(attrs={'rows': 4, 'cols': 10}),
        }

    def __init__(self, *args, **kwargs):
        super(ChatMessageForm, self).__init__(*args, **kwargs)
        # add common css class to all widgets
        for field in iter(self.fields):
            # get current classes from Meta
            classes = self.fields[field].widget.attrs.get("class")
            if classes is not None:
                classes += " form-control"
            else:
                classes = "form-control"
            self.fields[field].widget.attrs.update({
                "class": classes
            })

chat/views.py
#!python
# -*- coding: utf8 -*-

from django.http import JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.template.context_processors import csrf

from forms import ChatMessageForm
from models import *


def ajax_view(request):
    last_id = request.GET.get(u'lastmsg_id', None)
    current_order_id = request.GET.get(u'order', None)
    if last_id:
        msgs = ChatMessage.objects.filter(id__gt=int(last_id), order__id=int(current_order_id))[:1]
        result = iterations_ajax(request, msgs)
        return JsonResponse(result)
    else:
        return JsonResponse({'error': 'not loaded'})


def chat_view(request, id=None):
    if id is None:
        return render(request, 'please_login.html')
    else:
        args = {}
        args.update(csrf(request))
        args['form'] = ChatMessageForm()
        if request.user.id:
            args['order'] = id
            args['sender'] = request.user.id
            if 'message' in request.POST:
                form = ChatMessageForm(request.POST)
                if form.is_valid():
                    form.sender = request.user.id
                    form.save()
                    return redirect('./')
            else:
                user = request.user.id
                msgs = ChatMessage.objects.filter(order__id=id)
                args['msgs'] = iterations(request, msgs)
                if not msgs:
                    return render(request, 'please_login.html')

                if not args['msgs']:
                    return render(request, 'chat/chat.html', args)

                else:
                    if args['msgs'][0]['order_sender'] == user or args['msgs'][0]['order_destination'] == user:
                        return render(request, 'chat/chat.html', args)

                    else:
                        return render(request, 'please_login.html')

        else:
            return render(request, 'please_login.html')


def iterations(request, x):
    kek = []
    for msg in x:
        usefull_shit = dict(
            sender=msg.sender,
            sender_id=msg.sender.id,
            order=msg.order.id,
            date=msg.date,
            message=msg.message,
            id=msg.id,
            style=''
        )
        try:
            usefull_shit['order_sender'] = msg.order.user.id
        except AttributeError:
            usefull_shit['order_sender'] = 0

        try:
            usefull_shit['order_destination'] = msg.order.destination.id
        except AttributeError:
            usefull_shit['order_destination'] = 0

        if usefull_shit['sender_id'] == request.user.id:
            usefull_shit['style'] = 'fpv'  # first person view
        else:
            usefull_shit['style'] = 'tpv'  # third person view
        kek.append(usefull_shit)
    return tuple(kek)


def iterations_ajax(request, x):
    usefull_shit = dict()
    for msg in x:
        usefull_shit = dict(
            sender=str(msg.sender),
            sender_id=str(msg.sender.id),
            order=str(msg.order.id),
            oder_destination=msg.order.destination.user.id,
            date=msg.date,
            message=msg.message,
            id=msg.id,
            style=''
        )
        try:
            usefull_shit['order_sender'] = str(msg.order.user.id)
        except AttributeError:
            usefull_shit['order_sender'] = 0

        try:
            usefull_shit['order_destination'] = str(msg.order.destination.id)
        except AttributeError:
            usefull_shit['order_destination'] = 0

        if usefull_shit['sender_id'] == str(request.user.id):
            usefull_shit['style'] = 'fpv'  # first person view
        else:
            usefull_shit['style'] = 'tpv'  # third person view
    return usefull_shit

chat/templates/chat/chat.html
{%  extends 'base.html' %}
{% load staticfiles %}

{% block headertext %}
    <h1>Обсудите заказ в реальном времени!</h1>
{% endblock %}

{% block content %}

<div class="chat-window container-outside">
{% if msgs %}
 {% for msg in msgs %}
    <div class="msg {{ msg.style }}">
        <h5>{{ msg.sender }} | {{ msg.date |date:'Y-m-d H:i' }}</h5>
        <div class="msg-text">
            <p>
                {{ msg.message }}
            </p>
            </br id="{{ msg.id }}">
        </div>
    </div>
 {% endfor %}

{% endif %}
</div>

<form method="POST" action="./">
{% csrf_token %}

   <input id="id_order" name="order" type="hidden" value="{{ order }}">
   <input id="id_sender" name="sender" type="hidden" value="{{ sender }}">
    <div id="chat_message">
    <p>{{ form.message }}</p>

    <button type="submit" class="btn btn-primary chat-button">Отправить</button>
    </div>
</form>

{% endblock %}

{% block javascript %}
<script>
/**
 * Created by qed on 27.03.17.
 */

var ajax_id = '{% with msgs|last as last %}{{ last.id }}{% endwith %}';
var ajax_order = '{% with msgs|last as last %}{{ last.order }}{% endwith %}';

function get_id() {
            if (ajax_id == '{% with msgs|last as last %}{{ last.id }}{% endwith %}')
            {
                return ajax_id
            } else {
                return ajax_id
            }
}

function get_order() {
    if (ajax_order == '{% with msgs|last as last %}{{ last.order }}{% endwith %}') {
        return ajax_order
    } else {
        return ajax_order
    }
}



function AjaxCall() {
   var foo = $.ajax({
    //type: 'POST',
    url:'{% url "chat_ajax" %}',
    data: {
        "lastmsg_id":get_id(),
        "order": get_order(),
    },
    datatype: 'json',
    success: function(data) {
       if (data.error){
           console.log(data.error);
       }
       if (data.message) {
           $('<div class="msg new-msgs" id="msg_'+data.id+'"></div>').appendTo(".chat-window");
           $('#msg_' + data.id).addClass(data.style)
           $('<h5>' + data.sender + ' | ' + data.date + '</h5>').appendTo("#msg_"+data.id);
           $('<div class="msg-text" id="text_'+data.id+'"></div>').appendTo("#msg_"+data.id);
           $('<p>' + data.message + '</p>').appendTo("#text_"+data.id);
           $('</br id="'+ data.id +'">').appendTo("#text_"+data.id);
           $('.chat-window').scrollTop($('.chat-window')[0].scrollHeight);
           ajax_id = data.id;
           ajax_order = data.order;
 }
    },
    error: function() { console.log["error"] }
    });
}

function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

window.onload = function(){
    $('.chat-window').scrollTop($('.chat-window')[0].scrollHeight);
    $('#id_message').attr('placeholder', 'Введите сообщение');
    $('html, body').animate({
        scrollTop: $('.chat-window').offset().top - 20
    }, 'fast');
    $('#id_message').keypress(function(e) {
        if(e.which == 13) {
            jQuery(this).blur();
            jQuery('.btn').focus().click();
        }
    });
};
setInterval(AjaxCall, 200);

</script>
{% endblock %}