b2b/urls.py
#!python
# -*- coding: utf8 -*-


from django.conf.urls import url
from views import *


urlpatterns = [
    url(r'register/$', register, name="b2b_register"),
]

grill/urls.py
#!python
# -*- coding: utf8 -*-

""" Адреса уровня проекта

grill URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sample/', include('sample.urls')),
    url(r'^', include('b2c.urls')),
    url(r'^user/', include('logit.urls')),
    url(r'^user/', include('django.contrib.auth.urls'), name="login"),
    url(r'', include('content.urls')),
    url(r'^redactor', include('redactor.urls')),
    url(r'^paypal', include('paypal.standard.ipn.urls')),
    url(r'^', include('transactions.urls')),
    url(r'^market/', include('market.urls')),
    url(r'^b2b/', include('b2b.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^accounts/', include('account.urls')),
    url(r'^comments/', include('comments.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', bidmarket, name="market_orders"),
    url(r'^my_orders/$', received_orders, name="my_orders"),
    url(r'^order_(?P<id>\d+)$', show_order, name="market_order"),
    url(r'^private/$', private_all, name="private_all"),
    url(r'^private_(?P<id>\d+)$', private_one, name="private_one"),
]

b2c/models.py
#!python
# -*- coding: utf8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import User


class Order(models.Model):
    NEW = 'new'
    ACTIVE = 'active'
    DECLINED = 'declined'
    FINISHED = 'finished'
    STATUS_CHOICES = (
        (NEW, 'Новый'),
        (ACTIVE, 'В работе'),
        (DECLINED, 'Отказ'),
        (FINISHED, 'Выполнен'),
    )
    status = models.CharField(choices=STATUS_CHOICES, default=NEW, max_length=50, blank=False)
    email = models.EmailField(_(u'Email'))
    datetime = models.DateTimeField(_(u'Время создания'), default=timezone.now)
    sender = models.CharField(_(u'Отправитель'), max_length=50)
    user = models.ForeignKey(
        User,
        related_name='order_user',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    phone = models.CharField(_(u'Телефон'), max_length=15, blank=True)
    destination = models.ForeignKey(
        'b2b.Printer',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    service = models.CharField(_(u'Услуга'), max_length=50)
    comment = models.TextField(_(u'Комментарий'))
    categories = models.ForeignKey(
        'b2b.Categories',
        on_delete=models.CASCADE,
        default='',
        null=True,
    )
    tags = models.ManyToManyField('b2b.Tags')
    market = models.BooleanField(_(u'На рынке заявок'), default=False)
    responses = models.ManyToManyField('b2b.Printer', blank=True, related_name='order_responses')

    class Meta:
        verbose_name = _(u'Заявка')
        verbose_name_plural = _(u'Заявки')

    def __unicode__(self):
        return self.service

market/models.py
#!python
# -*- coding: utf8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import User


class MarketComment(models.Model):
    datetime = models.DateTimeField(_(u'Время создания'), default=timezone.now)
    comment = models.TextField(_(u'Комментарий'))
    sender = models.ForeignKey(
        'b2b.Printer',
        on_delete=models.CASCADE,
        null=True,
    )
    order = models.ForeignKey(
        'b2c.Order',
        on_delete=models.CASCADE,
        null=True,
    )

    class Meta:
        verbose_name = _(u'Комментарий')
        verbose_name_plural = _(u'Комментарии')

    def __unicode__(self):
        return str(self.id)

market/forms.py
#!python
# -*- coding: utf8 -*-

from django.forms import ModelForm

from models import *


class MarketCommentForm(ModelForm):
    class Meta:
        model = MarketComment
        exclude = ['datetime']

    def __init__(self, *args, **kwargs):
        super(MarketCommentForm, self).__init__(*args, **kwargs)
        # add common css class to all widgets
        for field in iter(self.fields):
            # get current classes from Meta
            classes = self.fields[field].widget.attrs.get("class")
            if classes is not None:
                classes += " form-control"
            else:
                classes = "form-control"
            self.fields[field].widget.attrs.update({
                "class": classes
            })

market/views.py
#!python
# -*- coding: utf8 -*-

from django.shortcuts import redirect, render
from django.template.context_processors import csrf
from django.utils import timezone

from b2b.models import Printer
from b2c.forms import *
from forms import *
from datetime import datetime
import pytz


def bidmarket(request):
    if request.user.id:
        args = {}
        args.update(csrf(request))
        if 'response_order' in request.POST:
            current = Order.objects.get(id=int(request.POST['response_order']))
            responder = Printer.objects.get(id=int(request.POST['responder']))
            if responder.sub_expires.astimezone(pytz.UTC) > pytz.utc.localize(datetime.now()):
                current.responses.add(responder)
            else:
                return render(request, 'please_subscribe.html')

        user = request.user.id
        try:
            printer_user = Printer.objects.get(user__id=user)
            args['printer_id'] = printer_user.id
        except AttributeError:
            return render(request, 'please_login.html')
        except Printer.DoesNotExist:
            return render(request, 'please_login.html')
        try:
            orders = Order.objects.filter(market=True).exclude(user__isnull=True).order_by('datetime').reverse()[:100]
        except Order.DoesNotExist:
            return render(request, 'please_login.html')
        list = prepare_orders(orders)
        args['orders'] = list
        args['is_printer'] = True
        args['page'] = 'market_orders'
        return render(request, 'market/market.html', args)
    else:
        return render(request, 'please_login.html')


def received_orders(request):
    if request.user.id:
        orders = Order.objects.filter(destination__user_id=request.user.id).order_by('datetime').reverse()
        list = prepare_orders(orders)
        return render(request, 'market/received_orders.html',
                      {'orders': list, 'id': request.user.id, 'is_printer': True, 'page': 'my_orders'})
    else:
        return render(request, 'please_login.html')


def show_order(request, id=None):
    if id is None:
        return redirect('./')
    else:
        args = {}
        if request.user.id:
            user = request.user.id
            # If comment added
            if 'comment' in request.POST:
                sender = Printer.objects.get(id=int(request.POST['sender']))
                if sender.sub_expires and sender.sub_expires.astimezone(pytz.UTC) > pytz.utc.localize(datetime.now()):
                    form = MarketCommentForm(request.POST)
                    if form.is_valid():
                        form.save()
                        return redirect('market_order', id=id)

                else:
                    return render(request, 'please_subscribe.html')

            # If response added
            elif 'response_order' in request.POST:
                current = Order.objects.get(id=int(request.POST['response_order']))
                responder = Printer.objects.get(id=int(request.POST['responder']))
                if responder.sub_expires and responder.sub_expires.astimezone(pytz.UTC) > pytz.utc.localize(datetime.now()):
                    current.responses.add(responder)
                else:
                    return render(request, 'please_subscribe.html')

            # If status changed
            elif 'status' in request.POST:
                instance = Order.objects.get(id=int(id))
                form = StatusForm(request.POST, instance=instance)
                if form.is_valid():
                    form.save()
                    return redirect('market_order', id=id)

            # Find out if an order exists
            try:
                order = Order.objects.get(id=int(id))
                # If current user got this order
                try:
                    if order.destination.user.id == user:
                        args['select'] = StatusForm(request.POST or None, instance=order)
                except AttributeError:
                    pass
                args['comments'] = []
                # Find current user's typography
                try:
                    printer_user = Printer.objects.get(user__id=user)
                    args['printer'] = dict(
                        id=printer_user.id,
                        user_id=printer_user.user.id,
                        name=printer_user.name
                    )
                except AttributeError:
                    return render(request, 'please_login.html')

                except Printer.DoesNotExist:
                    return render(request, 'please_login.html')

                # Get comments
                comments = MarketComment.objects.filter(order__id=int(id)).order_by('datetime')
                for comment in comments:
                    comment_data = dict(
                        id=comment.id,
                        datetime=comment.datetime,
                        comment=comment.comment,
                        sender=comment.sender,
                        sender_id=comment.sender.id,
                    )
                    args['comments'].append(comment_data)
                tuple(args['comments'])
                args.update(csrf(request))
                order_sorted = sort_order(order)
                args['order'] = order_sorted
                args['form'] = MarketCommentForm
                args['is_printer'] = True
                args['page'] = 'market_order'
                return render(request, 'market/show_order.html', args)

            except Order.DoesNotExist:
                return render(request, 'market/show_order.html',
                              {'error': 'DoesNotExist: matching order does not exist'})

        else:
            return render(request, 'please_login.html')


def private_all(request):
    if request.user.id:
        orders = Order.objects.filter(user_id=request.user.id).order_by('datetime').reverse()
        list = prepare_orders(orders)
        return render(request, 'market/received_orders.html',
                      {'orders': list, 'id': request.user.id, 'private': True, 'page': 'private_all', 'is_printer': False})

    else:
        return render(request, 'please_login.html')


def private_one(request, id=None):
    if id is None:
        return redirect('./')

    else:
        if 'destination' in request.POST:
            instance = Order.objects.get(id=int(id))
            form = SetDestinationForm(request.POST, instance=instance)
            if form.is_valid():
                form.save()
                return redirect('private_one', id=id)

        if request.user.id:
            # If order exists
            try:
                order = Order.objects.get(id=int(id))
                # if user is the creator
                if order.user.id == request.user.id:
                    args = {'is_private': True, 'is_printer': False}
                    order_sorted = sort_order(order)
                    args['order'] = order_sorted
                    args['comments'] = []
                    # Get comments
                    comments = MarketComment.objects.filter(order__id=int(id)).order_by('datetime')
                    for comment in comments:
                        comment_data = dict(
                            id=comment.id,
                            datetime=comment.datetime,
                            comment=comment.comment,
                            sender=comment.sender,
                            sender_id=comment.sender.id,
                        )
                        args['comments'].append(comment_data)
                    tuple(args['comments'])
                    args.update(csrf(request))
                    args['destination'] = SetDestinationForm(instance=order)
                    args['page'] = 'private_one'
                    try:
                        args['destination_id'] = order.destination.id
                    except AttributeError:
                        pass
                    return render(request, 'market/show_order.html', args)

                else:
                    return render(request, 'please_login.html')

            except Order.DoesNotExist:
                return render(request, 'market/show_order.html',
                              {'error': 'DoesNotExist: matching order does not exist'})

        else:
            return render(request, 'please_login.html')


def sort_order(order):
    now = timezone.now()
    order_data = dict(
        id=order.id,
        market=order.market,
        status=order.get_status_display(),
        email=order.email,
        phone=order.phone,
        datetime=order.datetime,
        sender=order.sender,
        user=order.user,
        service=order.service,
        comment=order.comment,
        destination=order.destination,
    )
    # Get the tuple of respondents
    responses = order.responses.values()
    order_data['responses'] = {}
    for response in responses:
        order_data['responses'][response['id']] = response

    # Find out if order.destination.id exists (if an order is taken)
    try:
        order.destination.id
        order_data['taken'] = 1
    except AttributeError:
        order_data['taken'] = 0

    # Count full hours between now and when the order was created
    time_diff_hours = divmod((now - order.datetime).total_seconds(), 3600)[0]

    # Mark 3+ hours old unprocessed orders red, the new ones green,
    if order.status == 'new':
        if time_diff_hours >= 3:
            order_data['tr_class'] = 'tr-market-red'
        else:
            order_data['tr_class'] = 'tr-market-green'
    return order_data


def prepare_orders(orders):
    list = []

    for order in orders:
        order_data = sort_order(order)
        list.append(order_data)
    tuple(list)  # Tuples weigh less and process faster then lists
    return list

market/templates/market/market.html
{% extends "account/personal_account.html" %}

{% block headtitle %}
    Рынок заявок
{% endblock %}

{% block account %}
    <table class="table table-bordered">
        <tr>
            <th> Время </th>
            <th> Клиент </th>
            <th> Почта </th>
            <th> Статус </th>
            <th> Заголовок </th>
            <th> Комментарий </th>
        </tr>
        {% for order in orders %}
            <tr
                    {% if order.taken == 1 %}
                        class="tr-market-grey"
                    {% endif %}
            >
                <td> {{ order.datetime |date:'Y-m-d H:i' }} </td>
                <td> {{ order.sender }} </td>
                <td> {{ order.email }} </td>
                <td> {{ order.status }} </td>
                <td> {{ order.service }} </td>
                <td> {{ order.comment }} </td>
            </tr >
            <tr>
                <td colspan="6">
                    {% if order.taken == 1 %}
                        <b>Заказ назначен.</b>
                    {% else %}
                        <b>Откликов: {{ order.responses|length }}. </b>
                        {% if printer_id in order.responses %}
                            <b>Вы откликнулись на заказ. </b>
                        {% else %}

                            <button form="submit_form" type="submit" class="btn btn-info">Откликнуться</button>
                        {% endif %}
                    {% endif %}
                        <a type="button" class="btn btn-info" href="{% url 'market_order' id=order.id  %}">Перейти к заказу</a>
                    {% if printer_id not in order.responses %}
                        <form id="submit_form" method='post' action="{% url 'market_order' id=order.id  %}">
                                {% csrf_token %}
                                <input type="hidden" id="id_responder" name="responder" value="{{ printer_id }}" required>
                                <input type="hidden" id="id_response_order" name="response_order" value="{{ order.id }}" required>
                        </form>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

market/templates/market/received_orders.html
{% extends "account/personal_account.html" %}

{% block headtitle %}
    Полученные заявки
{% endblock %}

{% block account %}
    <table class="table table-bordered">
        <tr>
            <th> Время </th>
            <th> Клиент </th>
            <th> Номер телефона </th>
            <th> Почта </th>
            {% if select %}<th> Статус </th>{% endif %}
            <th> Заголовок </th>
            <th> Комментарий </th>
        </tr>
        {% for order in orders %}
            <tr {% if order.tr_class %} class="{{order.tr_class}}" {% endif %}>
                <td> {{ order.datetime |date:'Y-m-d H:i' }} </td>
                <td> {{ order.sender }} </td>
                <td> {{ order.phone }} </td>
                <td> {{ order.email }} </td>
                {% if select %}
                    <td>
                        <form action="{% url 'market_order' id=order.id  %}" method="POST">
                        {% csrf_token %}
                        {{ select.status }}
                        </form>
                    </td>
                {% endif %}
                <td> {{ order.service }} </td>
                <td> {{ order.comment }} </td>
            </tr>
            <tr>
                <td colspan="7">
                    {% if order.destination %}
                        <a type="button" class="btn btn-info" href="{% url 'chat' id=order.id  %}">Перейти к чату</a>
                    {% endif %}
                        <a type="button" class="btn btn-info" href="
                        {% if private %}
                            {% url 'private_one' id=order.id  %}
                        {% else %}
                            {% url 'market_order' id=order.id  %}
                        {% endif %}">
                        Перейти к заказу
                        </a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

market/templates/market/show_order.html
{% extends "account/personal_account.html" %}

{% block headtitle %}
    Посмотреть заявку
{% endblock %}

{% block account %}
    {% if error %}

    {% else %}
        <table class="table table-bordered">
            <tr>
                <th> Время </th>
                <th> Клиент </th>
                {% if select or is_private %}<th> Номер телефона </th>{% endif %}
                <th> Почта </th>
                {% if select or is_private %}<th> Статус </th>{% endif %}
                <th> Заголовок </th>
                <th> Комментарий </th>
            </tr>
            <tr
                    {% if order.taken == 1 %}
                        class="tr-market-grey"
                    {% endif %}
            >
                <td> {{ order.datetime |date:'Y-m-d H:i' }} </td>
                <td> {{ order.sender }} </td>
                {% if select or is_private %}<td> {{ order.phone }} </td>{% endif %}
                <td> {{ order.email }} </td>
                {% if select %}<td> <form action="{% url 'market_order' id=order.id  %}" method="POST">{% csrf_token %} {{ select.status }} </form></td>{% endif %}
                {% if is_private %}<td> {{ order.status }} </td>{% endif %}
                <td> {{ order.service }} </td>
                <td> {{ order.comment }} </td>
            </tr >
            <tr>
                <td colspan="7">
                    {% if order.taken == 1 %}
                        {% if select %}
                            <b> Вы назначены исполнителем. </b>
                        <a type="button" class="btn btn-info" href="{% url 'chat' id=order.id  %}">Перейти к чату</a>
                        {% else %}
                            <b>Заказ назначен.</b>
                            <a type="button" class="btn btn-info" href="{% url 'chat' id=order.id  %}">Перейти к чату</a>
                        {% endif %}
                    {% else %}
                        <b>Откликов: {{ order.responses|length }}. </b>
                        {% if not is_private %}
                            {% if printer.id in order.responses %}
                                <b>Вы откликнулись на заказ</b>
                            {% else %}
                                <form method='post' action="{% url 'market_order' id=order.id  %}">
                                    {% csrf_token %}
                                    <input type="hidden" id="id_responder" name="responder" value="{{ printer.id }}" required>
                                    <input type="hidden" id="id_response_order" name="response_order" value="{{ order.id }}" required>
                                    <button type="submit" class="btn btn-info">Откликнуться</button>
                                </form>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                    {% if is_private %}
                        <form action="{% url 'private_one' id=order.id  %}" method="POST">
                            {% csrf_token %}
                            <label for="id_destination">Исполнитель: </label>
                            <select id="id_destination" name="destination" onchange="this.form.submit()">
                                <option value="" selected="selected">---------</option>
                                {% for key, val in order.responses.items %}
                                <option value="{{ key }}" {% if destination_id == key%}selected="selected" {% endif %}>{{ val.name }}</option>
                                {% endfor %}
                            </select>
                        </form>
                    {% endif %}
                </td>
            </tr>
        </table>
        {% if comments %}
            <div>
            {% for comment in comments %}
                <div class="comment">
                    <h5>{{ comment.sender }} | {{ comment.datetime |date:'Y-m-d H:i' }}</h5>
                    <div>
                        <p>
                            {{ comment.comment }}
                        </p>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% endif %}
        {% if order.taken == 0 and not is_private %}
            <div  class="comment">
                <form method='post' action="{% url 'market_order' id=order.id  %}">
                    {% csrf_token %}
                    <input type="hidden" id="id_sender" name="sender" value="{{ printer.id }}" required>
                    <input type="hidden" id="id_order" name="order" value="{{ order.id }}" required>
                    <label for="id_comment">Добавить комментарий:</label>
                    {{ form.comment }}
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Отправить</button>
                    </div>
                </form>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}