b2b/urls.py
#!python
# -*- coding: utf8 -*-


from django.conf.urls import url
from views import *


urlpatterns = [
    url(r'register/$', register, name="b2b_register"),
]

b2c/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', map, name="map"),
    url('^market/order/$', market, name="market"),
    url('^market/success/$', market_success, name="market_success"),
]

grill/urls.py
#!python
# -*- coding: utf8 -*-

""" Адреса уровня проекта

grill URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sample/', include('sample.urls')),
    url(r'^', include('b2c.urls')),
    url(r'^user/', include('logit.urls')),
    url(r'^user/', include('django.contrib.auth.urls'), name="login"),
    url(r'', include('content.urls')),
    url(r'^redactor', include('redactor.urls')),
    url(r'^paypal', include('paypal.standard.ipn.urls')),
    url(r'^', include('transactions.urls')),
    url(r'^market/', include('market.urls')),
    url(r'^b2b/', include('b2b.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^accounts/', include('account.urls')),
    url(r'^comments/', include('comments.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', bidmarket, name="market_orders"),
    url(r'^my_orders/$', received_orders, name="my_orders"),
    url(r'^order_(?P<id>\d+)$', show_order, name="market_order"),
    url(r'^private/$', private_all, name="private_all"),
    url(r'^private_(?P<id>\d+)$', private_one, name="private_one"),
]

b2c/models.py
#!python
# -*- coding: utf8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import User


class Order(models.Model):
    NEW = 'new'
    ACTIVE = 'active'
    DECLINED = 'declined'
    FINISHED = 'finished'
    STATUS_CHOICES = (
        (NEW, 'Новый'),
        (ACTIVE, 'В работе'),
        (DECLINED, 'Отказ'),
        (FINISHED, 'Выполнен'),
    )
    status = models.CharField(choices=STATUS_CHOICES, default=NEW, max_length=50, blank=False)
    email = models.EmailField(_(u'Email'))
    datetime = models.DateTimeField(_(u'Время создания'), default=timezone.now)
    sender = models.CharField(_(u'Отправитель'), max_length=50)
    user = models.ForeignKey(
        User,
        related_name='order_user',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    phone = models.CharField(_(u'Телефон'), max_length=15, blank=True)
    destination = models.ForeignKey(
        'b2b.Printer',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    service = models.CharField(_(u'Услуга'), max_length=50)
    comment = models.TextField(_(u'Комментарий'))
    categories = models.ForeignKey(
        'b2b.Categories',
        on_delete=models.CASCADE,
        default='',
        null=True,
    )
    tags = models.ManyToManyField('b2b.Tags')
    market = models.BooleanField(_(u'На рынке заявок'), default=False)
    responses = models.ManyToManyField('b2b.Printer', blank=True, related_name='order_responses')

    class Meta:
        verbose_name = _(u'Заявка')
        verbose_name_plural = _(u'Заявки')

    def __unicode__(self):
        return self.service

b2c/views.py
#!python
# -*- coding: utf8 -*-

from django.db.models import Q
from django.shortcuts import redirect
from django.shortcuts import render
from django.template.context_processors import csrf
from b2b.models import Printer, Tags
from forms import OrderForm
from datetime import datetime


def map(request, template='b2c/map.html'):
    args = {}
    args.update(csrf(request))
    args['form'] = OrderForm
    args['printers'] = []
    if request.user.id:
        user = request.user
        args['user_id'] = request.user.id
        args['user_first_name'] = user.first_name
        args['user_last_name'] = user.last_name
        args['user_email'] = user.email

    tags = Tags.objects.distinct()
    mystring = ''
    for tag in tags:
        mydict = u'%d:%s' % (tag.id, '[' + (", ".join(str(p.id) for p in tag.cat.all())) + ']')
        mystring = u'%s, %s' % (mystring, mydict)

    args['tags'] = '{%s}' % (mystring[2:])

    if 'filter' in request.POST and request.POST['filter']:
        filter = request.POST['filter']
        args['get'] = filter
        printers = Printer.objects.filter(Q(name__icontains=filter) | \
                                          Q(categories__category__icontains=filter) | \
                                          Q(tags__tag__icontains=filter)).filter(sub_expires__gt=datetime.now()).distinct().order_by('name')
    else:
        printers = Printer.objects.filter(sub_expires__gt=datetime.now()).order_by('name')
        if request.POST:
            form = OrderForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('./')

    # Fill marker template args
    for printer in printers:
        marker = dict(
            coords_name="lalo_" + str(printer.id),
            lat=str(printer.lat).replace(',', '.'),
            lon=str(printer.lon).replace(',', '.'),
            marker_name="marker_" + str(printer.id),
            address=printer.address,
            name=printer.name,
            id=printer.id,
            phone=printer.phone,
            website=printer.website,
            services=printer.services,
        )
        try:
            marker['logo'] = printer.logo.url
        except ValueError:
            marker['logo'] = None
        try:
            marker['metro'] = printer.metro
        except ValueError:
            marker['metro'] = "N/A"
        try:
            marker['schedule'] = printer.schedule
        except ValueError:
            marker['schedule'] = "N/A"
        args['printers'].append(marker)
    tuple(args['printers'])

    args['cycle'] = range(5)
    return render(request, template, args)


def market(request):
    if request.user.id:
        if request.POST:
            form = OrderForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('market_success')

        return map(request, template='b2c/market.html')
    else:
        return render(request, 'please_login.html')


def market_success(request):
        return render(request, 'b2c/market_success.html')


def sort_by_name_bubble(list):
    return True

market/views.py
#!python
# -*- coding: utf8 -*-

from django.shortcuts import redirect, render
from django.template.context_processors import csrf
from django.utils import timezone

from b2b.models import Printer
from b2c.forms import *
from forms import *
from datetime import datetime
import pytz


def bidmarket(request):
    if request.user.id:
        args = {}
        args.update(csrf(request))
        if 'response_order' in request.POST:
            current = Order.objects.get(id=int(request.POST['response_order']))
            responder = Printer.objects.get(id=int(request.POST['responder']))
            if responder.sub_expires.astimezone(pytz.UTC) > pytz.utc.localize(datetime.now()):
                current.responses.add(responder)
            else:
                return render(request, 'please_subscribe.html')

        user = request.user.id
        try:
            printer_user = Printer.objects.get(user__id=user)
            args['printer_id'] = printer_user.id
        except AttributeError:
            return render(request, 'please_login.html')
        except Printer.DoesNotExist:
            return render(request, 'please_login.html')
        try:
            orders = Order.objects.filter(market=True).exclude(user__isnull=True).order_by('datetime').reverse()[:100]
        except Order.DoesNotExist:
            return render(request, 'please_login.html')
        list = prepare_orders(orders)
        args['orders'] = list
        args['is_printer'] = True
        args['page'] = 'market_orders'
        return render(request, 'market/market.html', args)
    else:
        return render(request, 'please_login.html')


def received_orders(request):
    if request.user.id:
        orders = Order.objects.filter(destination__user_id=request.user.id).order_by('datetime').reverse()
        list = prepare_orders(orders)
        return render(request, 'market/received_orders.html',
                      {'orders': list, 'id': request.user.id, 'is_printer': True, 'page': 'my_orders'})
    else:
        return render(request, 'please_login.html')


def show_order(request, id=None):
    if id is None:
        return redirect('./')
    else:
        args = {}
        if request.user.id:
            user = request.user.id
            # If comment added
            if 'comment' in request.POST:
                sender = Printer.objects.get(id=int(request.POST['sender']))
                if sender.sub_expires and sender.sub_expires.astimezone(pytz.UTC) > pytz.utc.localize(datetime.now()):
                    form = MarketCommentForm(request.POST)
                    if form.is_valid():
                        form.save()
                        return redirect('market_order', id=id)

                else:
                    return render(request, 'please_subscribe.html')

            # If response added
            elif 'response_order' in request.POST:
                current = Order.objects.get(id=int(request.POST['response_order']))
                responder = Printer.objects.get(id=int(request.POST['responder']))
                if responder.sub_expires and responder.sub_expires.astimezone(pytz.UTC) > pytz.utc.localize(datetime.now()):
                    current.responses.add(responder)
                else:
                    return render(request, 'please_subscribe.html')

            # If status changed
            elif 'status' in request.POST:
                instance = Order.objects.get(id=int(id))
                form = StatusForm(request.POST, instance=instance)
                if form.is_valid():
                    form.save()
                    return redirect('market_order', id=id)

            # Find out if an order exists
            try:
                order = Order.objects.get(id=int(id))
                # If current user got this order
                try:
                    if order.destination.user.id == user:
                        args['select'] = StatusForm(request.POST or None, instance=order)
                except AttributeError:
                    pass
                args['comments'] = []
                # Find current user's typography
                try:
                    printer_user = Printer.objects.get(user__id=user)
                    args['printer'] = dict(
                        id=printer_user.id,
                        user_id=printer_user.user.id,
                        name=printer_user.name
                    )
                except AttributeError:
                    return render(request, 'please_login.html')

                except Printer.DoesNotExist:
                    return render(request, 'please_login.html')

                # Get comments
                comments = MarketComment.objects.filter(order__id=int(id)).order_by('datetime')
                for comment in comments:
                    comment_data = dict(
                        id=comment.id,
                        datetime=comment.datetime,
                        comment=comment.comment,
                        sender=comment.sender,
                        sender_id=comment.sender.id,
                    )
                    args['comments'].append(comment_data)
                tuple(args['comments'])
                args.update(csrf(request))
                order_sorted = sort_order(order)
                args['order'] = order_sorted
                args['form'] = MarketCommentForm
                args['is_printer'] = True
                args['page'] = 'market_order'
                return render(request, 'market/show_order.html', args)

            except Order.DoesNotExist:
                return render(request, 'market/show_order.html',
                              {'error': 'DoesNotExist: matching order does not exist'})

        else:
            return render(request, 'please_login.html')


def private_all(request):
    if request.user.id:
        orders = Order.objects.filter(user_id=request.user.id).order_by('datetime').reverse()
        list = prepare_orders(orders)
        return render(request, 'market/received_orders.html',
                      {'orders': list, 'id': request.user.id, 'private': True, 'page': 'private_all', 'is_printer': False})

    else:
        return render(request, 'please_login.html')


def private_one(request, id=None):
    if id is None:
        return redirect('./')

    else:
        if 'destination' in request.POST:
            instance = Order.objects.get(id=int(id))
            form = SetDestinationForm(request.POST, instance=instance)
            if form.is_valid():
                form.save()
                return redirect('private_one', id=id)

        if request.user.id:
            # If order exists
            try:
                order = Order.objects.get(id=int(id))
                # if user is the creator
                if order.user.id == request.user.id:
                    args = {'is_private': True, 'is_printer': False}
                    order_sorted = sort_order(order)
                    args['order'] = order_sorted
                    args['comments'] = []
                    # Get comments
                    comments = MarketComment.objects.filter(order__id=int(id)).order_by('datetime')
                    for comment in comments:
                        comment_data = dict(
                            id=comment.id,
                            datetime=comment.datetime,
                            comment=comment.comment,
                            sender=comment.sender,
                            sender_id=comment.sender.id,
                        )
                        args['comments'].append(comment_data)
                    tuple(args['comments'])
                    args.update(csrf(request))
                    args['destination'] = SetDestinationForm(instance=order)
                    args['page'] = 'private_one'
                    try:
                        args['destination_id'] = order.destination.id
                    except AttributeError:
                        pass
                    return render(request, 'market/show_order.html', args)

                else:
                    return render(request, 'please_login.html')

            except Order.DoesNotExist:
                return render(request, 'market/show_order.html',
                              {'error': 'DoesNotExist: matching order does not exist'})

        else:
            return render(request, 'please_login.html')


def sort_order(order):
    now = timezone.now()
    order_data = dict(
        id=order.id,
        market=order.market,
        status=order.get_status_display(),
        email=order.email,
        phone=order.phone,
        datetime=order.datetime,
        sender=order.sender,
        user=order.user,
        service=order.service,
        comment=order.comment,
        destination=order.destination,
    )
    # Get the tuple of respondents
    responses = order.responses.values()
    order_data['responses'] = {}
    for response in responses:
        order_data['responses'][response['id']] = response

    # Find out if order.destination.id exists (if an order is taken)
    try:
        order.destination.id
        order_data['taken'] = 1
    except AttributeError:
        order_data['taken'] = 0

    # Count full hours between now and when the order was created
    time_diff_hours = divmod((now - order.datetime).total_seconds(), 3600)[0]

    # Mark 3+ hours old unprocessed orders red, the new ones green,
    if order.status == 'new':
        if time_diff_hours >= 3:
            order_data['tr_class'] = 'tr-market-red'
        else:
            order_data['tr_class'] = 'tr-market-green'
    return order_data


def prepare_orders(orders):
    list = []

    for order in orders:
        order_data = sort_order(order)
        list.append(order_data)
    tuple(list)  # Tuples weigh less and process faster then lists
    return list

b2c/templates/b2c/map.html
{% extends "base.html" %}

{% block headtitle %}
    Найти печатника
{% endblock %}

{% block headertext %}
    <h1>Найдите печатника поблизости и сделайте заказ!</h1>
{% endblock %}

{% block filter %}
    <form class="form-group" accept-charset="utf-8" role="search" method='post' action="{% url 'map' %}">

        <div class="form-row">
          <div class="col-xs-11 search-bar">
            <input name="filter" id="filter" type="text" class="form-control" placeholder="{{ get }}">
          </div>
          <div class="col-xs-1 search-bar">
              <button type="submit" class="form-control btn-default spyglass">
                  <i class="fa fa-search" aria-hidden="true"></i>
              </button>
          </div>
        {% csrf_token %}
        </div>
    </form>
{% endblock %}

{% block content %}

<div class="table-view">
    <div class="table-view-row">

<div id="map-b2c"></div>
    <div class="container printers-container">
     <div class="printers-list-header">
         <h3 style="color: white;">   Список компаний    </h3>
     </div>
     <div class="printers-list">
         {% if printers %}
            {% for entry in printers %}
                <div class="shadow-container" data-lat="{{ entry.lat }}" data-lon="{{ entry.lon }}">
                    <div style="display: flex;" >
                        <div>
                            <img class="text-uppercase" style="width: 100px; height: 100px; display: block" src="{{ entry.logo }}"></img>
                            <div class="some-printer rating" style="display: block">
                            {% for i in cycle %}
                               <i class="fa fa-star-o" aria-hidden="true"></i>
                            {% endfor %}
                            </div>
                        </div>
                        <div class="some-printer rating" style="flex-grow: 0;">
                        <div class="printer-info-short">
                            <h4 class="printer-name" style="font-weight: bold; font-size: 110%; text-align: center;">{{ entry.name }} </h4>
                            <span style="font-weight: bold">Адрес: </span><span style="font-style: oblique;">{{ entry.address }} </span> </br>
                            <span style="font-weight: bold">Метро: </span><span style="font-style: oblique;">{{ entry.metro }} </span> </br>
                        </div>
                        <div class="printer-info-full">
                            <span style="font-weight: bold">Время работы: </span><span style="font-style: oblique;">{{ entry.schedule }} </span> </br>
                            <span style="font-weight: bold">Перечень услуг: </span> <span style="font-style: oblique"> {{ entry.services }} </span> </br>
                        </div>
                        </div>
                    </div>
                    <div id="buttons">
                    <button class="btn btn-primary make-call" data-id="{{ entry.id }}" data-name="{{ entry.name }}">Сделать заказ</button>
                    <a target="_blank" href="{% url 'comments' id=entry.id %}" class="btn btn-primary reviews">Отзывы</a>
                    </div>
                </div>
            {% endfor %}
     {% endif %}
     </div>
    </div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="ModalLabel">Оформить заказ</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <form method='post' action="">
              {% csrf_token %}
              <div class="modal-body">
                  <div class="form-group row">
                      <label for="id_sender" class="col-sm-2 col-form-label">Ваше имя:</label>
                      <div class="col-sm-10">
                          {{ form.sender }}
                      </div>
                      {% if user_id %}<input id="id_user" name="user" type="hidden" value="{{ user_id }}" />{% endif %}
                  </div>
                  <div class="form-group row">
                      <label class="col-sm-2 col-form-label">Кому:</label>
                      <div class="col-sm-10">
                          <input class="form-control" id="fake_destination" readonly="readonly" maxlength="50" type="text"/>
                          <input id="id_destination" name="destination" type="hidden" value="" required />
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="id_service" class="col-sm-2 col-form-label">Вид услуги:</label>
                      <div class="col-sm-10">
                          {{ form.service }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="id_comment" class="col-sm-2 col-form-label">Комментарии к заказу:</label>
                      <div class="col-sm-10">
                          {{ form.comment }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="id_email" class="col-sm-2 col-form-label">Контактный Email:</label>
                      <div class="col-sm-10">
                          {{ form.email }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="id_phone" class="col-sm-2 col-form-label">Контактный телефон:</label>
                      <div class="col-sm-10">
                          {{ form.phone }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label for="id_categories" class="col-sm-2 col-form-label">Категория:</label>
                      <div class="col-sm-10">
                          {{ form.categories }}
                      </div>
                  </div>
                  <div class="form-group row">
                      <label class="col-sm-2 col-form-label">Теги:</label>
                      <div class="col-sm-10">
                          {{ form.tags }}
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                  <button type="submit" class="btn btn-primary">Отправить</button>
              </div>
          </form>
      </div>
  </div>
</div>

  <!-- wrapper end !-->
</div>
</div>
<script src="http://maps.google.com/maps/api/js?key=AIzaSyCIC6deUmipx1i53t2ncZlP7MUTeQ52qvY"></script>

<script>

function restyleChboxes(){
    var chboxes = $("[id*='id_tags_']");
    $(chboxes).parents("label").unwrap();
    $.each(chboxes, function() {
        var currentChbox = $(this);
        //Change input group style
        $(currentChbox).parent("label").addClass("form-check-label");
        $(currentChbox).addClass('form-check-input');
        $(currentChbox).parent().wrap("<div class='form-check'></div>");
    })
    $('#id_tags').wrap("<fieldset class='form-group'></fieldset>");
    sortChboxes();
}

function sortChboxes(){
    var chboxes = $("[id*='id_tags_']"),
        selected = $('#id_categories').find(":selected"),
        chboxDict = {{ tags |safe }};
    $.each(chboxes, function() {
        $(this).prop('checked', false);
        if ($.inArray(parseInt(selected.val()), chboxDict[$(this).val()]) != -1){
            $(this).parent().show();
        } else {
            $(this).parent().hide();
        }
    })

}

function fillForm(){
    $('#id_sender').val('{{ user_first_name }} {{ user_last_name }}');
    $('#id_email').val('{{user_email}}');
}

function showPopup(name, id){
    $('#myModal').modal('show');
    $('#fake_destination').val(name);
    $('#id_destination').val(id);
}

var map;

function setGoogleMapCoords(lat, lon){

	// ! $scope is for AngularJS, use common variables instead

	// set latln by latitude and longitude
	var latLng = new google.maps.LatLng(lat, lon);
	console.log(lat, lon);

	// set map options, use previously set latln as map center
	var mapOptions = {
        center: latLng,
        zoom: 15,
        mapTypeId: google.maps.MapTypeId.ROADMAP
	};

	// create a new map
	map = new google.maps.Map(document.getElementById("map-b2c"), mapOptions);

	// 3.1 Add a marker
	google.maps.event.addListenerOnce(map, 'idle', function(){
        var marker = new google.maps.Marker({
            map: map, // select map to put the marker on
            animation: google.maps.Animation.DROP, // animation
            position:  latLng// where to put a marker
        });

    {% for printer in printers %}
        var {{ printer.coords_name }} = new google.maps.LatLng({{ printer.lat }}, {{ printer.lon }});
        var {{ printer.marker_name }} = new google.maps.Marker({
            map: map, // select map to put the marker on
            animation: google.maps.Animation.DROP, // animation
            position: {{ printer.coords_name }},
            icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
        });
        //meta
        {{ printer.marker_name }}.id = '{{ printer.id }}';
        {{ printer.marker_name }}.name = '{{ printer.name }}';
        {{ printer.marker_name }}.address = '{{ printer.address }}';
        {{ printer.marker_name }}.logo = '{{ printer.logo }}';
        {{ printer.marker_name }}.addListener('click', function() {showPopup(this.name, this.id)});
    {% endfor %}

	});
}

// call

window.onload = function(){
    console.log('window is loaded');
    restyleChboxes();
    fillForm();

    $('.shadow-container').click(function ( event ) {
        var flatitude = parseFloat($(event.target).parents('.shadow-container').attr('data-lat') );
        var flongitude = parseFloat($(event.target).parents('.shadow-container').attr('data-lon') );
        map.setCenter({lat: flatitude, lng: flongitude});
    });

    $('.name').click(function ( event ) {
        $(event.target).parents('.shadow-container').find('.printer-info-full').slideToggle(200);
    });

    $('.make-call').click(function (event) {
        var fid = $(event.target).attr('data-id');
        var fname = $(event.target).attr('data-name');
        showPopup(fname, fid);
    });

    navigator.geolocation.getCurrentPosition(
        function(position) {
            console.log('geo is loaded');
        setGoogleMapCoords(position.coords.latitude, position.coords.longitude);
        },
        function(err){
            console.warn(`geo ERROR(${err.code}): ${err.message}`);

            var latLong;
            $.getJSON("http://ipinfo.io", function(ipinfo){
                console.log("Found location ["+ipinfo.loc+"] by ipinfo.io");
                latLong = ipinfo.loc.split(",");
                console.log(latLong);
             setGoogleMapCoords(latLong[0], latLong[1]);
            });
        }
    );

    $( "#id_categories" ).change(function() {
		sortChboxes();
	});
};



</script>
{% endblock %}

b2c/templates/b2c/market.html
{% extends "base.html" %}

{% block headtitle %}
    Рынок заказов
{% endblock %}

{% block headertext %}
    <h1>Разместите заказ и выберите лучшее предложение!</h1>
{% endblock %}

{% block content %}
	<form method='post' action="./">
		{% csrf_token %}
		<div class="modal-body">
			<input id="id_market" name="market" type="hidden" value="on">
			<div class="form-group row">
				<label for="id_sender" class="col-sm-2 col-form-label">От:</label>
				<div class="col-sm-10">
					{{ form.sender }}
				</div>
                <input id="id_user" name="user" type="hidden" value="{{ user_id }}" />
			</div>
			<div class="form-group row">
				<label for="id_service" class="col-sm-2 col-form-label">Услуга:</label>
				<div class="col-sm-10">
					{{ form.service }}
				</div>
			</div>
			<div class="form-group row">
				<label for="id_comment" class="col-sm-2 col-form-label">Описание:</label>
				<div class="col-sm-10">
					{{ form.comment }}
				</div>
			</div>
			<div class="form-group row">
				<label for="id_email" class="col-sm-2 col-form-label">Контактный Email:</label>
				<div class="col-sm-10">
					{{ form.email }}
				</div>
			</div>
			<div class="form-group row">
				<label for="id_phone" class="col-sm-2 col-form-label">Контактный телефон:</label>
				<div class="col-sm-10">
					{{ form.phone }}
				</div>
			</div>
			<div class="form-group row">
				<label for="id_categories" class="col-sm-2 col-form-label">Категория:</label>
				<div class="col-sm-10">
					{{ form.categories }}
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Теги:</label>
				<div class="col-sm-10">
					{{ form.tags }}
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button type="submit" class="btn btn-primary">Отправить</button>
		</div>
	</form>

<script>

	function restyleChboxes(){
		var chboxes = $("[id*='id_tags_']");
		$(chboxes).parents("label").unwrap();
		$.each(chboxes, function() {
			var currentChbox = $(this);
			//Change input group style
			$(currentChbox).parent("label").addClass("form-check-label");
			$(currentChbox).addClass('form-check-input');
			$(currentChbox).parent().wrap("<div class='form-check'></div>");
		})
		$('#id_tags').wrap("<fieldset class='form-group'></fieldset>");
		sortChboxes();
	}
	function sortChboxes(){
		var chboxes = $("[id*='id_tags_']"),
			selected = $('#id_categories').find(":selected"),
			chboxDict = {{ tags |safe }};
		$.each(chboxes, function() {
			$(this).prop('checked', false);
			if ($.inArray(parseInt(selected.val()), chboxDict[$(this).val()]) != -1){
				$(this).parent().show();
			} else {
				$(this).parent().hide();
			}
		})

	}
	function fillForm(){
        $('#id_sender').val('{{ user_first_name }} {{ user_last_name }}');
        $('#id_email').val('{{user_email}}');
    }
	// call
	window.onload = function(){
	    fillForm();
		restyleChboxes();
		$( "#id_categories" ).change(function() {
			sortChboxes();
		});
	}

</script>
{% endblock %}